/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLLER.GestiorFitxersTXT;
import DATA.Querys;

/**
 *
 * @author Usuari
 */
public class frmAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmAdmin.class.getName());

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() {
        initComponents();
        txtData.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEntranaments = new javax.swing.JButton();
        btnUsuaris = new javax.swing.JButton();
        cbmInfo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblInfo);

        jLabel1.setText("ADMINISTRADOR");

        btnEntranaments.setText("GESTIO ENTRANAMENTS");
        btnEntranaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntranamentsActionPerformed(evt);
            }
        });

        btnUsuaris.setText("GESTIO USUARIS");
        btnUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarisActionPerformed(evt);
            }
        });

        cbmInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estadístiques", "Registres", "Entrenaments" }));
        cbmInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmInfoActionPerformed(evt);
            }
        });

        jLabel2.setText("DATA");

        jLabel3.setText("INFORMACIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbmInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnEntranaments)
                        .addGap(105, 105, 105)
                        .addComponent(btnUsuaris))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntranaments)
                    .addComponent(btnUsuaris))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntranamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntranamentsActionPerformed
        // TODO add your handling code here:
        frmEntranaments f = new frmEntranaments();
        f.setVisible(true);
        GestiorFitxersTXT.escripturaAFitxerLog("Obrin formulari entrenaments");
    }//GEN-LAST:event_btnEntranamentsActionPerformed

    private void btnUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarisActionPerformed
        // TODO add your handling code here:
        frmUsuari f = new frmUsuari();
        f.setVisible(true);
        GestiorFitxersTXT.escripturaAFitxerLog("Obrin formulari usuaris");
    }//GEN-LAST:event_btnUsuarisActionPerformed

    private void cbmInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmInfoActionPerformed
        // TODO add your handling code here:

        String opcio = (String) cbmInfo.getSelectedItem();

        switch (opcio) {

            case "Estadístiques":
                txtData.setEnabled(false);
                Querys.mostrarEstadistiques();
                OmpirEstadistiques();
                break;

            case "Registres":
                txtData.setEnabled(true);
                OmplirRegistres();
                break;

            case "Entrenaments":
                txtData.setEnabled(false);
                Querys.mostrarEntrenaments();
                OmplirEntrenaments();
                break;
        }

    }//GEN-LAST:event_cbmInfoActionPerformed

    private void OmplirEntrenaments() {
        String[] columnes = {
            "ID", "DATA", "DURADA", "DISTANCIA",
            "DESCRIPCIO", "INTENSITAT", "COMPLETAT",
            "ID_USUARI", "ID_TIPUS"
        };

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel();

        model.setColumnIdentifiers(columnes);

        for (MODEL.Entrenament e : CONTROLLER.Principal.entrenaments) {

            Object[] fila = {
                e.getId(),
                e.getData(),
                e.getDuradaMinuts(),
                e.getDistancia(),
                e.getDescripcio(),
                e.getIntensitat(),
                e.isCompletat(),
                e.getUsuariId(),
                e.getTipusEsportId()
            };

            model.addRow(fila);
        }

        tblInfo.setModel(model);
        GestiorFitxersTXT.escripturaAFitxerLog("Omplim la taula d'entrenaments");
    }

    private void OmplirRegistres() {

    }

    private void OmpirEstadistiques() {
        String[] columnes = {
            "ESPORT", "TOTAL ENTRENAMENTS", "USUARIS ACTIUS", "MINUTS ACTIUS",
            "KM TOTALS", "MITJANA DURADA", "COMPLETATS"
        };

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel();

        model.setColumnIdentifiers(columnes);

        for (MODEL.Estadistica e : CONTROLLER.Principal.estadistiques) {

            Object[] fila = {
                e.getEsport(),
                e.getTotalEntrenaments(),
                e.getUsuarisActius(),
                e.getMinutsTotals(),
                e.getKmTotals(),
                e.getMitjanaDurada(),
                e.getCompletats()
            };

            model.addRow(fila);
        }

        tblInfo.setModel(model);

        GestiorFitxersTXT.escripturaAFitxerLog(
                "Omplim la taula d'estadistiques"
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntranaments;
    private javax.swing.JButton btnUsuaris;
    private javax.swing.JComboBox<String> cbmInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtData;
    // End of variables declaration//GEN-END:variables

}
