/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLLER.GestiorFitxersTXT;
import DATA.Querys;
import static DATA.Querys.afegirComentari;
import MODEL.Comentari;
import MODEL.Comentarientrenament;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuari
 */
public class frmEntranador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmEntranador.class.getName());

    /**
     * Creates new form frmEntranador
     */
    public frmEntranador() {
        GestiorFitxersTXT.escripturaAFitxerLog("Formulari entrenador iniciat");
        initComponents();

        Querys.mostrarEntrenaments();
        GestiorFitxersTXT.escripturaAFitxerLog("Entrenaments carregats des de la base de dades");
        omplirTaulaEntrenaments();
        GestiorFitxersTXT.escripturaAFitxerLog("Taula d'entrenaments omplerta");
        afegirListennerTaulaEntrenament();
        GestiorFitxersTXT.escripturaAFitxerLog("Listener de selecció d'entrenaments activat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntranaments = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentari = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnAfegirComentari = new javax.swing.JButton();
        ckValidar = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblComentaris = new javax.swing.JTable();
        txtIdEntrenador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ENTRANADOR");

        tblEntranaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEntranaments);

        txtComentari.setColumns(20);
        txtComentari.setRows(5);
        jScrollPane2.setViewportView(txtComentari);

        jLabel2.setText("Comentari");

        btnAfegirComentari.setText("AFEGIR COMENTARI");
        btnAfegirComentari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirComentariActionPerformed(evt);
            }
        });

        ckValidar.setText("VALIDAR");

        tblComentaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblComentaris);

        jLabel3.setText("ID ENTRENADOR");

        jLabel4.setText("ENTRENAMENTS");

        jLabel5.setText("COMENTARIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ckValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAfegirComentari)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(38, 38, 38)
                                    .addComponent(txtIdEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(40, 40, 40))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(289, 289, 289))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(542, 542, 542)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtIdEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(btnAfegirComentari)
                        .addGap(43, 43, 43)
                        .addComponent(ckValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfegirComentariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirComentariActionPerformed
        // TODO add your handling code here:
        int fila = tblEntranaments.getSelectedRow();

        if (fila != -1) {
            Integer idEntranament = (Integer) tblEntranaments.getModel().getValueAt(fila, 0);
            Integer idEntrenador = Integer.parseInt(txtIdEntrenador.getText());
            String text = txtComentari.getText();
            LocalDate data = LocalDate.now();
            afegirComentari(text,
                    data, idEntrenador, idEntranament);
            int filaSeleccionada = tblEntranaments.getSelectedRow();
            GestiorFitxersTXT.escripturaAFitxerLog(
                    "Comentari afegit correctament a l'entrenament ID: " + idEntranament
            );
            if (filaSeleccionada != -1) {

                // Agafem el ID de l'entrenament (columna 0)
                int idEntrenament = Integer.parseInt(
                        tblEntranaments.getValueAt(filaSeleccionada, 0).toString()
                );

                // Carrega comentaris
                Querys.mostrarComentari(idEntrenament);
                GestiorFitxersTXT.escripturaAFitxerLog(
                        "Comentaris carregats de l'entrenament ID: " + idEntrenament
                );
                // Omple la taula comentaris
                omplirTaulaComentaris();
                GestiorFitxersTXT.escripturaAFitxerLog(
                        "Taula de comentaris actualitzada"
                );
            } else {
                JOptionPane.showMessageDialog(this, "Selcciona una fila");
                GestiorFitxersTXT.escripturaAFitxerLog(
                        "Error: intent d'afegir comentari sense seleccionar entrenament"
                );
            }
    }//GEN-LAST:event_btnAfegirComentariActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public void omplirTaulaEntrenaments() {

        String[] columnes = {
            "ID", "DATA", "DURADA", "DISTANCIA",
            "DESCRIPCIO", "INTENSITAT", "COMPLETAT",
            "ID_USUARI", "ID_TIPUS"
        };

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel();

        model.setColumnIdentifiers(columnes);

        for (MODEL.Entrenament e : CONTROLLER.Principal.entrenaments) {

            Object[] fila = {
                e.getId(),
                e.getData(),
                e.getDuradaMinuts(),
                e.getDistancia(),
                e.getDescripcio(),
                e.getIntensitat(),
                e.isCompletat(),
                e.getUsuariId(),
                e.getTipusEsportId()
            };

            model.addRow(fila);
        }

        tblEntranaments.setModel(model);
        GestiorFitxersTXT.escripturaAFitxerLog(
                "Taula d'entrenaments omplerta correctament"
        );
    }

    public void omplirTaulaComentaris() {

        String[] columnes = {
            "ID",
            "TEXT",
            "DATA",
            "ENTRENAMENT_ID",
            "ENTRENADOR_ID"
        };

        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(columnes);

        for (Comentari c : CONTROLLER.Principal.comentaris) {

            Object[] fila = {
                c.getId(),
                c.getText(),
                c.getData(),
                c.getEntrenamentId(),
                c.getEntrenadorId()
            };

            model.addRow(fila);
        }

        tblComentaris.setModel(model);
        GestiorFitxersTXT.escripturaAFitxerLog(
                "Taula de comentaris omplerta correctament"
        );
    }

    private void afegirListennerTaulaEntrenament() {

        tblEntranaments.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {

                // Evita que es dispari dues vegades
                if (!e.getValueIsAdjusting()) {

                    int filaSeleccionada = tblEntranaments.getSelectedRow();

                    if (filaSeleccionada != -1) {

                        // Agafem el ID de l'entrenament (columna 0)
                        int idEntrenament = Integer.parseInt(
                                tblEntranaments.getValueAt(filaSeleccionada, 0).toString()
                        );
                        GestiorFitxersTXT.escripturaAFitxerLog(
                                "Entrenament seleccionat amb ID: " + idEntrenament
                        );
                        // Carrega comentaris
                        Querys.mostrarComentari(idEntrenament);
                        GestiorFitxersTXT.escripturaAFitxerLog(
                                "Comentaris carregats per l'entrenament ID: " + idEntrenament
                        );
                        // Omple la taula comentaris
                        omplirTaulaComentaris();
                        GestiorFitxersTXT.escripturaAFitxerLog(
                                "Taula de comentaris actualitzada"
                        );
                    }
                }
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmEntranador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirComentari;
    private javax.swing.JCheckBox ckValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblComentaris;
    private javax.swing.JTable tblEntranaments;
    private javax.swing.JTextArea txtComentari;
    private javax.swing.JTextField txtIdEntrenador;
    // End of variables declaration//GEN-END:variables

}
