/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLLER.GestiorFitxersTXT;
import DATA.Querys;
import MODEL.Entrenament;
import MODEL.TipusEsport;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;

/**
 *
 * @author Usuari
 */
public class frmEsportista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmEsportista.class.getName());

    /**
     * Creates new form frmEsportista
     */
    public frmEsportista() {
        initComponents();

        Querys.mostrarEntrenaments();
        omplirTaulaEntrenaments();
        carregarTipusEsport();
        carregarIntensitats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntrenaments = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbmIntensitat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        chkCompletat = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        btnEntrenament = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDurada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbmTipus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEntrenaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEntrenaments);

        jLabel1.setText("ESPORTISTA");

        cbmIntensitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmIntensitatActionPerformed(evt);
            }
        });

        jLabel3.setText("INTENSITAT");

        btnFiltrar.setText("FILTRAR");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        chkCompletat.setText("COMPLETAT");

        jLabel4.setText("DISTANCIA");

        jLabel5.setText("DATA");

        btnEntrenament.setText("GESTIONAR ENTRENAMENT");
        btnEntrenament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrenamentActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        jLabel7.setText("DURADA");

        txtDurada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuradaActionPerformed(evt);
            }
        });

        jLabel8.setText("TIPUS ESPORT");

        cbmTipus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmTipusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnFiltrar)
                                .addGap(67, 67, 67)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntrenament)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDurada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkCompletat)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbmIntensitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(155, 155, 155)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(261, 261, 261)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDurada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbmIntensitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkCompletat)
                            .addComponent(cbmTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFiltrar)
                            .addComponent(btnCancelar))
                        .addGap(59, 59, 59)
                        .addComponent(btnEntrenament)
                        .addGap(123, 123, 123))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarIntensitats() {

        cbmIntensitat.removeAllItems();

        try {

            ResultSet rs = Querys.getIntensitats();

            if (rs.next()) {

                String enumValue = rs.getString(2);

                enumValue = enumValue
                        .replace("enum(", "")
                        .replace(")", "")
                        .replace("'", "");

                String[] values = enumValue.split(",");

                for (String v : values) {
                    cbmIntensitat.addItem(v.trim());
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void carregarTipusEsport() {

        cbmTipus.removeAllItems();

        try {
            ResultSet rs = Querys.getTipusEsport();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nom = rs.getString("nom");

                cbmTipus.addItem(new TipusEsport(id, nom));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void omplirTaulaEntrenaments() {

        String[] columnes = {
            "ID", "DATA", "DURADA", "DISTANCIA",
            "DESCRIPCIO", "INTENSITAT", "COMPLETAT",
            "ID_USUARI", "ID_TIPUS"
        };

        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel();

        model.setColumnIdentifiers(columnes);

        for (MODEL.Entrenament e : CONTROLLER.Principal.entrenaments) {

            Object[] fila = {
                e.getId(),
                e.getData(),
                e.getDuradaMinuts(),
                e.getDistancia(),
                e.getDescripcio(),
                e.getIntensitat(),
                e.isCompletat(),
                e.getUsuariId(),
                e.getTipusEsportId()
            };

            model.addRow(fila);
        }

        tblEntrenaments.setModel(model);
    }

    private void btnEntrenamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrenamentActionPerformed
        // TODO add your handling code here:
        frmEntranaments f = new frmEntranaments();
        f.setVisible(true);
        GestiorFitxersTXT.escripturaAFitxerLog("Obrin formulari entrenaments");

    }//GEN-LAST:event_btnEntrenamentActionPerformed

    private void txtDuradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuradaActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        try {
            Integer id = txtId.getText().isEmpty() ? null : Integer.parseInt(txtId.getText());

            LocalDate data = txtData.getText().isEmpty()
                    ? null
                    : LocalDate.parse(txtData.getText()); // FORMAT: yyyy-MM-dd

            Integer durada = txtDurada.getText().isEmpty()
                    ? null
                    : Integer.parseInt(txtDurada.getText());

            Integer distancia = txtDistancia.getText().isEmpty()
                    ? null
                    : Integer.parseInt(txtDistancia.getText());

            Entrenament.Intensitat intensitat
                    = cbmIntensitat.getSelectedItem() == null
                    || cbmIntensitat.getSelectedItem().equals("Totes")
                    ? null
                    : Entrenament.Intensitat.valueOf(
                            cbmIntensitat.getSelectedItem().toString().toUpperCase()
                    );

            Boolean completat = chkCompletat.isSelected() ? true : null;

            Integer tipus = null;
            if (cbmTipus.getSelectedItem() != null && !cbmTipus.getSelectedItem().equals("Tots")) {
                tipus = Integer.parseInt(cbmTipus.getSelectedItem().toString());
            }

            Querys.filtrarEntrenament(id, data, durada, distancia, intensitat, completat, tipus);

            omplirTaulaEntrenaments();

        } catch (Exception e) {
            // javax.swing.JOptionPane.showMessageDialog(this, "Error en els filtres!");
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtData.setText("");
        txtDurada.setText("");
        txtDistancia.setText("");
        cbmIntensitat.setSelectedIndex(0);
        cbmTipus.setSelectedIndex(0);

        chkCompletat.setSelected(false);

    }//GEN-LAST:event_btnCancelarActionPerformed


    private void cbmIntensitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmIntensitatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbmIntensitatActionPerformed

    private void cbmTipusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmTipusActionPerformed
        // TODO add your handling code here:
        TipusEsport t = (TipusEsport) cbmTipus.getSelectedItem();
        int idSeleccionat = t.getId();

    }//GEN-LAST:event_cbmTipusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmEsportista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEntrenament;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbmIntensitat;
    private javax.swing.JComboBox<TipusEsport> cbmTipus;
    private javax.swing.JCheckBox chkCompletat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEntrenaments;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtDurada;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
