/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLLER.GestiorFitxersTXT;
import DATA.Querys;
import MODEL.Usuari;
import MODEL.Usuari.Rol;

/**
 *
 * @author Usuari
 */
public class frmUsuari extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmUsuari.class.getName());

    /**
     * Creates new form frmUsuari
     */
    public frmUsuari() {
        initComponents();
        desactivarCamps();
        GestiorFitxersTXT.escripturaAFitxerLog("Formulari d'usuaris iniciat amb camps desactivats");
        
        Querys.mostrarUsuaris();
        omplirTaulaUsuaris();
        GestiorFitxersTXT.escripturaAFitxerLog("Taula d'usuaris carregada");
        
        listennerUsuari();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuaris = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbmTipus = new javax.swing.JComboBox<>();
        btnAfegir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUsuaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuaris);

        jLabel1.setText("NOM");

        jLabel2.setText("CONTRASENYA");

        jLabel4.setText("TIPUS");

        cbmTipus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esportista", "Entrenador", "Administrador" }));

        btnAfegir.setText("AFEGIR");
        btnAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel5.setText("USUARIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPassword)
                                .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAfegir)
                        .addGap(29, 29, 29)
                        .addComponent(btnModificar)
                        .addGap(43, 43, 43)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbmTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAfegir)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void listennerUsuari() {
        tblUsuaris.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {

                int fila = tblUsuaris.getSelectedRow();

                if (fila != -1) {
                    GestiorFitxersTXT.escripturaAFitxerLog("Usuari seleccionat de la taula");
                    activarCamps();
                    GestiorFitxersTXT.escripturaAFitxerLog("Camps i botons activats");
                    txtNom.setText(tblUsuaris.getValueAt(fila, 1).toString());
                    txtPassword.setText(tblUsuaris.getValueAt(fila, 2).toString());
                    cbmTipus.setSelectedItem(tblUsuaris.getValueAt(fila, 3).toString());
                }
            }
        });
    }
    
    public void activarCamps() {
        txtNom.setEnabled(true);
        txtPassword.setEnabled(true);
        cbmTipus.setEnabled(true);

        btnAfegir.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }

    public void desactivarCamps() {
        txtNom.setEnabled(false);
        txtPassword.setEnabled(false);
        cbmTipus.setEnabled(false);

        btnAfegir.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }
    private void btnAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirActionPerformed
        // TODO add your handling code here:
        String nom = txtNom.getText();

        String contrassenya = new String(txtPassword.getPassword());

        Rol rol = Rol.valueOf(
                cbmTipus.getSelectedItem().toString().trim().toUpperCase()
        );

        Querys.afegirUsuari(nom, contrassenya, rol);
       GestiorFitxersTXT.escripturaAFitxerLog("Usuari afegit: " + nom);

        Querys.mostrarUsuaris();
        omplirTaulaUsuaris();
        GestiorFitxersTXT.escripturaAFitxerLog("Taula actualitzada despres d'afegir usuari");

        txtNom.setText("");
        txtPassword.setText("");
        cbmTipus.setSelectedIndex(0);
        GestiorFitxersTXT.escripturaAFitxerLog("Camps del formulari buidats");

        tblUsuaris.clearSelection();

        desactivarCamps();
        GestiorFitxersTXT.escripturaAFitxerLog("Camps i botons desactivats");
    }//GEN-LAST:event_btnAfegirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        int fila = tblUsuaris.getSelectedRow();

        if (fila == -1) {
            System.out.println("Selecciona un usuari");
            GestiorFitxersTXT.escripturaAFitxerLog("Error: intent de modificar sense seleccionar usuari");
            return;
        }

        int id = (int) tblUsuaris.getValueAt(fila, 0);

        String nom = txtNom.getText();
        String contrassenya = new String(txtPassword.getPassword());

        Rol rol = Rol.valueOf(
                cbmTipus.getSelectedItem().toString().trim().toUpperCase()
        );

        Querys.modificarUsuari(id, nom, contrassenya, rol);
       GestiorFitxersTXT.escripturaAFitxerLog("Usuari modificat amb ID: " + id);

        Querys.mostrarUsuaris();
        omplirTaulaUsuaris();
        GestiorFitxersTXT.escripturaAFitxerLog("Taula actualitzada després de modificar usuari");

        txtNom.setText("");
        txtPassword.setText("");
        cbmTipus.setSelectedIndex(0);
        GestiorFitxersTXT.escripturaAFitxerLog("Camps buidats");

        tblUsuaris.clearSelection();

        desactivarCamps();
        GestiorFitxersTXT.escripturaAFitxerLog("Camps i botons desactivats");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tblUsuaris.getSelectedRow();

        if (fila == -1) {
            System.out.println("Selecciona un usuari");
            GestiorFitxersTXT.escripturaAFitxerLog("Error: intent d'eliminar sense seleccionar usuari");
            return;
        }

        int id = (int) tblUsuaris.getValueAt(fila, 0);

        Querys.eliminarUsuari(id);
        GestiorFitxersTXT.escripturaAFitxerLog("Usuari eliminat amb ID: " + id);

        Querys.mostrarUsuaris();
        omplirTaulaUsuaris();
        GestiorFitxersTXT.escripturaAFitxerLog("Taula actualitzada després d'eliminar usuari");

        txtNom.setText("");
        txtPassword.setText("");
        cbmTipus.setSelectedIndex(0);
        GestiorFitxersTXT.escripturaAFitxerLog("Camps buidats");

        tblUsuaris.clearSelection();

        desactivarCamps();
        GestiorFitxersTXT.escripturaAFitxerLog("Camps i botons desactivats");
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void omplirTaulaUsuaris() {
        String[] columnes = {"ID", "NOM", "CONTRASSENYA", "ROL"};

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.setColumnIdentifiers(columnes);

        for (MODEL.Usuari u : CONTROLLER.Principal.usuaris) {
            Object[] fila = {
                u.getId(),
                u.getNom(),
                u.getContassenya(),
                u.getRol()
            };
            model.addRow(fila);
        }

        tblUsuaris.setModel(model);
        GestiorFitxersTXT.escripturaAFitxerLog("Taula d'usuaris omplerta correctament");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmUsuari().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbmTipus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuaris;
    private javax.swing.JTextField txtNom;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
